In [6]:
import pandas as pd

In [4]:
# Read a sample of the data
prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
url = f"{prefix}yellow_tripdata_2021-06.csv.gz"
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-06.csv.gz'

In [7]:
df = pd.read_csv(url)

/tmp/ipykernel_6071/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [8]:
# Display first rows
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-06-01 00:13:26,2021-06-01 00:17:14,1.0,0.90,1.0,N,186,50,1.0,5.0,3.00,0.5,2.20,0.00,0.3,11.00,2.5
1,1.0,2021-06-01 00:32:23,2021-06-01 01:07:04,1.0,23.00,1.0,N,132,18,2.0,61.5,1.75,0.5,0.00,6.55,0.3,70.60,0.0
2,1.0,2021-06-01 00:12:15,2021-06-01 00:15:28,0.0,0.90,1.0,N,138,70,2.0,5.0,1.75,0.5,0.00,0.00,0.3,7.55,0.0
3,1.0,2021-06-01 00:35:00,2021-06-01 00:53:17,0.0,11.20,1.0,N,138,189,1.0,31.5,1.75,0.5,8.50,0.00,0.3,42.55,0.0
4,2.0,2021-06-01 00:31:01,2021-06-01 00:52:27,1.0,9.49,1.0,N,138,142,1.0,28.5,0.50,0.5,7.77,6.55,0.3,47.87,2.5

In [9]:
len(df)

2834264

In [7]:
df["VendorID"]

0          1.0
1          1.0
2          1.0
3          1.0
4          2.0
          ...
1369760    NaN
1369761    NaN
1369762    NaN
1369763    NaN
1369764    NaN
Name: VendorID, Length: 1369765, dtype: float64

In [8]:
df.dtypes

VendorID                 float64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  float64
 1   tpep_pickup_datetime   1369765 non-null  str
 2   tpep_dropoff_datetime  1369765 non-null  str
 3   passenger_count        1271413 non-null  float64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  float64
 6   store_and_fwd_flag     1271413 non-null  str
 7   PULocationID           1369765 non-null  int64
 8   DOLocationID           1369765 non-null  int64
 9   payment_type           1271413 non-null  float64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: float64(13), int64(2), str(3)
memory usage: 239.1 MB

In [10]:
df.shape

(1369765, 18)

In [12]:
dataType = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

dateColumns = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dataType,
    parse_dates=dateColumns
)

In [13]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  Int64
 1   tpep_pickup_datetime   1369765 non-null  datetime64[us]
 2   tpep_dropoff_datetime  1369765 non-null  datetime64[us]
 3   passenger_count        1271413 non-null  Int64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  Int64
 6   store_and_fwd_flag     1271413 non-null  string
 7   PULocationID           1369765 non-null  Int64
 8   DOLocationID           1369765 non-null  Int64
 9   payment_type           1271413 non-null  Int64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: Int64(6), datetime64[us](2), float64(9), string(1)
memory usage: 197.2 MB

In [15]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [17]:
!uv add sqlalchemy psycopg2-binary

Resolved 118 packages in 0.83ms
Checked 9 packages in 0.20ms

In [30]:
# create_engine builds the connection configuration to PostgreSQL
# text allows us to write raw SQL strings (used for TRUNCATE later)
from sqlalchemy import create_engine, text

# Define WHERE and HOW to connect to PostgreSQL
# format: postgresql://username:password@host:port/database_name
# does NOT open a connection yet — just stores the credentials
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [20]:
#creates the table in PostgreSQL but inserts zero rows
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [21]:
#This just prints the SQL CREATE TABLE statement to your screen so you can see it. 
# It doesn't do anything to the database — it's purely for inspection.
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [22]:
len(df)

1369765

In [32]:
# ! means run this as a terminal command from inside the Jupyter notebook
# uv add installs the package AND saves it to your project dependencies
# tqdm is the progress bar library we need for the ingestion loop
!uv add tqdm

Resolved 119 packages in 4.61s
⠙ Preparing packages... (0/1)                                                   ⠋ Preparing packages... (0/0)
⠙ Preparing packages... (0/1)-------------------     0 B/76.54 KiB
⠙ Preparing packages... (0/1)------------------- 16.00 KiB/76.54 KiB
⠹ Preparing packages... (0/1)m------------------ 32.00 KiB/76.54 KiB
⠹ Preparing packages... (0/1)m------------------ 32.00 KiB/76.54 KiB
⠹ Preparing packages... (0/1)30m------------ 48.00 KiB/76.54 KiB
⠹ Preparing packages... (0/1)---------- 64.00 KiB/76.54 KiB
⠹ Preparing packages... (0/1)---------- 76.54 KiB/76.54 KiB
Prepared 1 package in 355ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 409ms
 + tqdm==4.67.3

In [ ]:
# Import progress bar library — .auto detects notebook vs terminal automatically
from tqdm.auto import tqdm

# Recreate iterator fresh to avoid exhausted iterator bug
df_iter = pd.read_csv(
    url,
    dtype=dataType,
    parse_dates=dateColumns,
    chunksize=100000,
    iterator=True
)

# Pull first chunk to create table structure
first_chunk = next(df_iter)

# Create table structure only — no rows inserted yet
# replace means: drop and recreate the table if it exists
first_chunk.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')
print("Table created")

# Insert first chunk's actual data
first_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
print("Inserted first chunk:", len(first_chunk))

# Loop through all remaining chunks and insert them
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
    print("Inserted chunk:", len(df_chunk))

print("Done! All data inserted into yellow_taxi_data.")

Table created
Inserted first chunk: 100000

0it [00:00, ?it/s]

Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 100000
Inserted chunk: 69765
Done! All data inserted into yellow_taxi_data.